---
title: "Analysis of NASA meteorite landings data"
output:
  html_document: 
    toc: yes
---




```{r set-options, echo=FALSE, cache=FALSE}
options(width = 1900)
```

## Meteorite analysis

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(dplyr)
library(readr)
library(leaflet)
library(ggplot2)
library(knitr)
```

### Import data

```{r paged.print=TRUE}
meteorites <- read_csv(
  "Meteorite_Landings.csv", 
  col_types = cols(year = col_character())
) %>% 
  rename (mass = `mass (g)` ) %>% 
  mutate( 
    date =  as.POSIXct(year,format="%d/%m/%Y %H:%M:%OS"), 
    recency = 2020 - lubridate::year(date)
  )

kable(head(meteorites, 7))
```

### data exploration {.tabset .tabset-fade}

#### logg mass

```{r message=FALSE, warning=FALSE}
meteorites = meteorites %>% 
  filter( recency >= 0) %>% 
  mutate(
    log_mass = log10(mass)
  )
ggplot(meteorites, aes(x=log_mass)) + geom_histogram(col = "black")
```

#### Recency in years

```{r message=FALSE, warning=FALSE}
meteorites = meteorites %>% 
  filter( recency >= 0, recency < 200)

ggplot(meteorites, aes(x=recency)) + geom_histogram(col = "black", binwidth = 5)
```

#### Meteorite class

```{r, fig.width=13, fig.height=5}
meteorites %>% 
  group_by(recclass) %>%
  summarise(n=n()) %>%
  arrange(desc(n)) %>% 
  head(25) %>% 
  ggplot(aes(recclass, weight = n)) +
  geom_bar()
```

#### time series

```{r, fig.width=13, fig.height=5}
meteorites %>% ggplot(aes(x = date, y = mass)) + geom_line()
```

### leaflet map


Interactive map of astroid locations

```{r}
reds <- colorNumeric("Reds", domain = NULL)

labels = paste(sep = "<br>", meteorites$name, lubridate::year(meteorites$date))
leaflet(
  data = meteorites, 
  width = "1400px", height = "1100px",
  ) %>% 
  addTiles() %>%
  setView(5,50, zoom = 5) %>% 
  addCircleMarkers(
    ~reclong, ~reclat,
    label = ~labels, 
    radius = ~0.8*log_mass,stroke = TRUE, weight = 2,
    fillOpacity = .75,
    color = ~reds(recency)
  ) %>% 
  addLegend(
    pal = reds,
    values = ~recency, 
    group = "circles", position = "bottomleft", title = "recency (in years)"
  ) 
```

